resources:
  repositories:
    - repository: templates
      type: github
      name: Tereius/conan-azure-templates
      endpoint: Tereius

jobs:
- job: Android
  strategy:
    matrix:
      armv7Linux:
        imageName: "ubuntu-18.04"
        buildProfile: "androidArmv7LinuxHost"
      armv7Windows:
        imageName: "windows-2019"
        buildProfile: "androidArmv7WinHost"
  pool:
    vmImage: '$(imageName)'
  timeoutInMinutes: 0
  steps:
  - template: buildConanRecipe.yml@templates
    parameters: 
      conanEnv: {
        CONAN_USERNAME: "tereius",
        CONAN_CHANNEL: "stable",
        CONAN_REMOTES: "https://conan.privatehive.de/artifactory/api/conan/public-conan",
        CONAN_BASE_PROFILE_PATH: "./buildProfiles/$(buildProfile).profile",
        CONAN_BUILD_PROFILE: "default"
      }

- job: Linux
  pool:
    vmImage: "ubuntu-18.04"
  timeoutInMinutes: 0
  steps:
  - template: buildConanRecipe.yml@templates
    parameters:
      conanEnv: {
        CONAN_USERNAME: "tereius",
        CONAN_CHANNEL: "stable",
        CONAN_REMOTES: "https://conan.privatehive.de/artifactory/api/conan/public-conan",
        CONAN_BASE_PROFILE: "default"
      }

- job: Windows
  pool:
    vmImage: "windows-2019"
  timeoutInMinutes: 0
  steps:
  - template: buildConanRecipe.yml@templates
    parameters:
      conanEnv: {
        CONAN_USERNAME: "tereius",
        CONAN_CHANNEL: "stable",
        CONAN_REMOTES: "https://conan.privatehive.de/artifactory/api/conan/public-conan",
        CONAN_BASE_PROFILE: "default"
      }
      
- job: Macos
  pool:
    vmImage: "macOS-11"
  timeoutInMinutes: 0
  steps:
  - template: buildConanRecipe.yml@templates
    parameters:
      conanEnv: {
        CONAN_USERNAME: "tereius",
        CONAN_CHANNEL: "stable",
        CONAN_REMOTES: "https://conan.privatehive.de/artifactory/api/conan/public-conan",
        CONAN_BASE_PROFILE: "default"
      }
    
- job: Upload
  dependsOn:
  - Android
  - Linux
  - Windows
  - Macos
  condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'))
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - template: uploadConanRecipe.yml@templates
    parameters: 
      conanEnv: {
        CONAN_USERNAME: "tereius",
        CONAN_CHANNEL: "stable",
        CONAN_UPLOAD: "https://conan.privatehive.de/artifactory/api/conan/public-conan",
        CONAN_LOGIN_USERNAME: "ci",
        CONAN_PASSWORD: "$(secret)",
      }
